[SETTINGS]

; this disables free cam collision while making edits
disable_free_cam_collision_1 = true

; this disables free cam collision while the scene is playing
disable_free_cam_collision_2 = true

; this disables free cam collision while blending
disable_free_cam_collision_3 = true

; this keeps the streaming focus on the camera (so the world will have the highest quality around the camera)
attach_streaming_focus_to_camera = false

; the key to change above setting at run-time (see ReadMe.txt for a list of key codes)
; set this to -1 if you want to disable this feature
attach_streaming_focus_to_camera_key = 0x78

; maximum horizontal speed of the free camera (must be a positive number)
max_horizontal_free_cam_speed = 40

; maximum vertical speed of the free camera (must be a positive number)
max_vertical_free_cam_speed = 40

; this disables the profanity filter, allowing you to name your projects whatever the fuck you want
disable_profanity_filter = false