###################################################################################
###################################################################################
###########			============================================		###########
###########		 SixStarResponse Configuration by the Realism Team		###########
###########			============================================		###########
###########		Modify this INI at your own risk. Putting in arbirary	###########
###########             values may make your game do weird things       ###########
###################################################################################
###################################################################################



[Settings]
MinSpeedToBeConsideredEscapingInVehicle=10				#Minimum player speed (in m/s) required to trigger the fast despawn and respawn logic for spawned units that are lagging behind on a chase (set -1 to disable)
MinSpeedDiffForFastDespawn=10							#Speed difference (in m/s) between the player and a spawned unit to use the mininum range of parameters set below (if SpeedDiff <= 10 then Direction=-0.75; DistDivider=1.5)
MaxSpeedDiffForFastDespawn=50							#Speed difference (in m/s) between the player and a spawned unit to use the maximum range of parameters set below (if SpeedDiff >= 50 then Direction=-0.5; DistDivider=4.0)
MinDirectionForFastDespawn=-0.75						#Minimum direction threshold (as dot product) between the player and a spawned unit to trigger a fast despawn
MaxDirectionForFastDespawn=-0.5							#Maximum direction threshold (as dot product) between the player and a spawned unit to trigger a fast despawn (-0.5 = -60° => Unit needs to be inside a 120° cone behind the player)
MinDespawnDistDividerForFastDespawn=1.5					#Mininum despawn distance divider for fast despawns
MaxDespawnDistDividerForFastDespawn=3.0					#Maximum despawn distance divider for fast despawns (NewDespawnDistance = CurrentDespawnDistance/Divider)
DespawnImmunityTime=20									#How many seconds need to pass from the spawning of an unit before it can be despawned
FastDespawnImmunityTime=5								#How many seconds need to pass from the spawning of an unit before it can be despawned by the fast despawn logic
HighspeedPursuitMPHRequired=100							#This is the speed required for high speed pursuit in MPH.
ZoneChangeDelay=7                               		#how many seconds delay to change response zones. (too low of a number may toggle zones when you pass by them)
SixStarPedsKilledThreshold=35							#How many cops need to be killed by the player on 5 stars to get 6 stars
SevenStarPedsKilledThreshold=40							#How many cops need to be killed by the player on 6 stars to get 7 stars
EightStarPedsKilledThreshold=45							#How many cops need to be killed by the player on 7 stars to get 8 stars
NineStarPedsKilledThreshold=50							#How many cops need to be killed by the player on 8 stars to get 9 stars
TenStarPedsKilledThreshold=50							#How many cops need to be killed by the player on 9 stars to get 10 stars
RadarWantedLevel=4										#Minimum wanted level required for the aircraft radar to be active. While radar is active, police will detect the player when he's flying an aircraft over a specific height limit. Set 0 to disable. 
RadarDetectionHeight=100								#Minimum height in meters the player needs to fly for being detected by the radar.
RadarDetectHelicopters=1								#Specifies whether helicopters should be affected by the radar. By default, only planes will be detected. Set this to 1 to enable, 0 to disable.
SpawnedVehicleSpeed=35.0 								#This is the base speed spawned vehicles will have if player is on foot - when in vehicle, this speed is increased by 10 - won't go over vehicle max speed though
ShowPoliceBlips=1										#Set this to 0 if you want to disable all police blips
ShowBlipHeading=0										#Shows a black arrow indicating the heading of a blip (like online)
AmbientBackup=1											#Allows cops to call in backup when attacked by NPCs
AmbientBackupSpawnCap=50								#[Ambient Backup only:] Maximum amount of cops that can be spawned by the ambient backup system
MaxIncidentDistance=250									#[Ambient Backup only:] How far from the closest wanted NPC the player must be before resetting their wanted level
CrimeScoreMultiplier=2.5								#[Ambient Backup only:] How much faster NPCs can increase their wanted level compared to the player (only counts cop kills)
PoliceHeliWantedLvl=3									#[Ambient Backup only:] NPC Wanted Level required before dispatching Police Helicopters against them
SwatHeliWantedLvl=5										#[Ambient Backup only:] NPC Wanted Level required before dispatching Swat/Rappel Helicopters against them
DrivebyWantedLvl=5										#[Ambient Backup only:] NPC Wanted Level required for cops to perform drivebys
DrivebyHeliWantedLvl=4									#[Ambient Backup only:] NPC Wanted Level required for cops in helicopters to perform drivebys
HelicoptersRefuelTime=180								#[Ambient Backup only:] Number of seconds ambient backup helicopters can stay up before being called off for refueling
DefensiveCopsAtRoadblocks=1								#Allow cops spawned at roadblocks to behave defensively when in combat against the player
MaxResponse_1Star=2
MaxResponse_2Star=3
MaxResponse_3Star=5
MaxResponse_4Star=7
MaxResponse_5Star=10
MaxResponse_6Star=15
MaxResponse_7Star=17
MaxResponse_8Star=18
MaxResponse_9Star=19
MaxResponse_10Star=20
Disable=F10												#Set the key to enable and disable SSR (it's enabled on the start of the game). Disabling SSR allows for LSPDFR & Story Mode compatibility, but stops wanted level system from working.
DisableModifier=Control									#Modifier key that needs to be pressed with Disable key: allowed values: Control, Alt, Shift, None

[Debug]
Debug=0													#Setting to 1 turns on debug text
DebugErrorUI=0		
DebugNatives=0		
DebugStopwatch=0		
DebugTimeStamps=0										#setting this to 0 increases performance when debug mode is on
OverwriteLogEachRun=1
AmbientBackupMonitor=0
LogOnScreenLevel=WARN									#Minimum log level (out of VERBOSE, DEBUG, INFO, WARN, ERROR) to display on screen
LogToFileLevel=VERBOSE									#Minimum log level to print to SixStarResponse.log
#The following keys Only work if debug is set to 1#
ZoneName=F7
WantedToggle=F8
