[Script]
DebugNatives=false

; Prevents player and cops to get stuck inside / outside the prison
FixPrisonGates=true
; Prevents Cayo Perico scenario peds to be spawned below the ground when playing on North Yankton
FixCayoScenarioPeds=true
; Makes cops use some unused megaphone voice lines while on vehicle 
CopAdditionalSpeech=true
; Allow cops to use the searchlight in their cars while searching for the player									
ManageSearchlights=true
; Little HUD detail for the missions "The Paleto Score" and "The Big Score"
RealWantedLvlsForMissions=true
; Prevents Gang peds from fleeing when the player is being attacked by the cops
PreventGangsFromFleeingWhenAttackedByPolice=true