#!/usr/bin/env bash
# Regenerates Mods/MANIFEST.md: size + SHA-256 of every file in the OpenIV Mods/ folder.
# RPFs are too large for git, so this manifest is what gets committed instead.
# Usage (from Git Bash, game root): bash tools/update-mods-manifest.sh
set -euo pipefail
cd "$(dirname "$0")/.."

out="Mods/MANIFEST.md"
{
  echo "# Mods/ Manifest"
  echo
  echo "Generated by \`tools/update-mods-manifest.sh\`. Do not edit by hand."
  echo
  echo "| File | Size (bytes) | SHA-256 |"
  echo "|---|---:|---|"
  find Mods -type f ! -name MANIFEST.md ! -name '*.bak' -print0 | sort -z | while IFS= read -r -d '' f; do
    size=$(stat -c %s "$f")
    hash=$(sha256sum "$f" | cut -d' ' -f1)
    echo "| \`${f}\` | ${size} | \`${hash}\` |"
  done
} > "$out"
echo "Wrote $out"
